// <auto-generated />
namespace Com.Jamim.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _06dec11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_06dec11));
        
        string IMigrationMetadata.Id
        {
            get { return "201512052000598_06-dec-1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
